version: 0.0
os: linux
files:
  - source: /index.html
    destination: /var/www/html/
  - source: /exercise
    destination: /var/www/html/exercise
  - source: /hw1
    destination: /var/www/html/hw1
  - source: /hw2
    destination: /var/www/html/hw2
  - source: /hw3
    destination: /var/www/html/hw3
hooks:
  BeforeInstall:
    - location: scripts/install_dependencies
      timeout: 3000
      runas: root
    - location: scripts/start_server
      timeout: 3000
      runas: root
  ApplicationStop:
    - location: scripts/stop_server
      timeout: 3000
      runas: root

